// Generated by gencpp from file pack2/test.msg
// DO NOT EDIT!


#ifndef PACK2_MESSAGE_TEST_H
#define PACK2_MESSAGE_TEST_H

#include <ros/service_traits.h>


#include <pack2/testRequest.h>
#include <pack2/testResponse.h>


namespace pack2
{

struct test
{

typedef testRequest Request;
typedef testResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct test
} // namespace pack2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pack2::test > {
  static const char* value()
  {
    return "0bf7337b4741e03b661dce528144e36a";
  }

  static const char* value(const ::pack2::test&) { return value(); }
};

template<>
struct DataType< ::pack2::test > {
  static const char* value()
  {
    return "pack2/test";
  }

  static const char* value(const ::pack2::test&) { return value(); }
};


// service_traits::MD5Sum< ::pack2::testRequest> should match
// service_traits::MD5Sum< ::pack2::test >
template<>
struct MD5Sum< ::pack2::testRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pack2::test >::value();
  }
  static const char* value(const ::pack2::testRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pack2::testRequest> should match
// service_traits::DataType< ::pack2::test >
template<>
struct DataType< ::pack2::testRequest>
{
  static const char* value()
  {
    return DataType< ::pack2::test >::value();
  }
  static const char* value(const ::pack2::testRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pack2::testResponse> should match
// service_traits::MD5Sum< ::pack2::test >
template<>
struct MD5Sum< ::pack2::testResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pack2::test >::value();
  }
  static const char* value(const ::pack2::testResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pack2::testResponse> should match
// service_traits::DataType< ::pack2::test >
template<>
struct DataType< ::pack2::testResponse>
{
  static const char* value()
  {
    return DataType< ::pack2::test >::value();
  }
  static const char* value(const ::pack2::testResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PACK2_MESSAGE_TEST_H
