// Generated by gencpp from file pack2/testRequest.msg
// DO NOT EDIT!


#ifndef PACK2_MESSAGE_TESTREQUEST_H
#define PACK2_MESSAGE_TESTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pack2
{
template <class ContainerAllocator>
struct testRequest_
{
  typedef testRequest_<ContainerAllocator> Type;

  testRequest_()
    : ran(0.0)  {
    }
  testRequest_(const ContainerAllocator& _alloc)
    : ran(0.0)  {
  (void)_alloc;
    }



   typedef float _ran_type;
  _ran_type ran;





  typedef boost::shared_ptr< ::pack2::testRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pack2::testRequest_<ContainerAllocator> const> ConstPtr;

}; // struct testRequest_

typedef ::pack2::testRequest_<std::allocator<void> > testRequest;

typedef boost::shared_ptr< ::pack2::testRequest > testRequestPtr;
typedef boost::shared_ptr< ::pack2::testRequest const> testRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pack2::testRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pack2::testRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pack2::testRequest_<ContainerAllocator1> & lhs, const ::pack2::testRequest_<ContainerAllocator2> & rhs)
{
  return lhs.ran == rhs.ran;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pack2::testRequest_<ContainerAllocator1> & lhs, const ::pack2::testRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pack2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pack2::testRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pack2::testRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pack2::testRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pack2::testRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pack2::testRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pack2::testRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pack2::testRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0bf7337b4741e03b661dce528144e36a";
  }

  static const char* value(const ::pack2::testRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0bf7337b4741e03bULL;
  static const uint64_t static_value2 = 0x661dce528144e36aULL;
};

template<class ContainerAllocator>
struct DataType< ::pack2::testRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pack2/testRequest";
  }

  static const char* value(const ::pack2::testRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pack2::testRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 ran\n"
"\n"
;
  }

  static const char* value(const ::pack2::testRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pack2::testRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ran);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct testRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pack2::testRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pack2::testRequest_<ContainerAllocator>& v)
  {
    s << indent << "ran: ";
    Printer<float>::stream(s, indent + "  ", v.ran);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACK2_MESSAGE_TESTREQUEST_H
