// Generated by gencpp from file pack1/test.msg
// DO NOT EDIT!


#ifndef PACK1_MESSAGE_TEST_H
#define PACK1_MESSAGE_TEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pack1
{
template <class ContainerAllocator>
struct test_
{
  typedef test_<ContainerAllocator> Type;

  test_()
    : num(0)  {
    }
  test_(const ContainerAllocator& _alloc)
    : num(0)  {
  (void)_alloc;
    }



   typedef int8_t _num_type;
  _num_type num;





  typedef boost::shared_ptr< ::pack1::test_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pack1::test_<ContainerAllocator> const> ConstPtr;

}; // struct test_

typedef ::pack1::test_<std::allocator<void> > test;

typedef boost::shared_ptr< ::pack1::test > testPtr;
typedef boost::shared_ptr< ::pack1::test const> testConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pack1::test_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pack1::test_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pack1::test_<ContainerAllocator1> & lhs, const ::pack1::test_<ContainerAllocator2> & rhs)
{
  return lhs.num == rhs.num;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pack1::test_<ContainerAllocator1> & lhs, const ::pack1::test_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pack1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pack1::test_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pack1::test_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pack1::test_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pack1::test_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pack1::test_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pack1::test_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pack1::test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cf992509827662516557e7b1f30e20ce";
  }

  static const char* value(const ::pack1::test_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcf99250982766251ULL;
  static const uint64_t static_value2 = 0x6557e7b1f30e20ceULL;
};

template<class ContainerAllocator>
struct DataType< ::pack1::test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pack1/test";
  }

  static const char* value(const ::pack1::test_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pack1::test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 num\n"
"\n"
"\n"
;
  }

  static const char* value(const ::pack1::test_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pack1::test_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct test_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pack1::test_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pack1::test_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<int8_t>::stream(s, indent + "  ", v.num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACK1_MESSAGE_TEST_H
